steps:
- name: node:20.0.0
  entrypoint: npm
  args: ["install"]
- name: node:20.0.0
  entrypoint: npm
  args: ["run", "build"]
  serviceAccount: [soloway.ivan.412@gmail.com]
options:
  defaultLogsBucket: REGIONAL_USER_OWNED_BUCKET
timeout: "1600s"

