steps:
- name: node:20.0.0
  entrypoint: npm
  args: ["install"]
- name: node:20.0.0
  entrypoint: npm
  args: ["run", "build"]
options:
  defaultLogsBucket: REGIONAL_USER_OWNED_BUCKET
timeout: "1600s"

